# Site settings
title: Cengiz C. Mataracı
description: 'My Personal Page'
url: 'http://cengizcmataraci.me'
baseurl: ''
profilepic: '/images/profile.png'
bkimage: '/images/bk1.gif'
google_analytics: UA-XXXXXX-X
font_awesome: '2c6dd94fa4.js'

author:
  name: 'Cengiz C. Mataracı'
  email: cengizcmataraci@gmail.com
  brain: kablosuzbeyin
  github_username:  cengizcmataraci
  linkedin_username:  cengizcmataraci

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

