import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Profile from "../public/img/profile.png";

export default function Home() {
  // let el = document.getElementsByClassName("profile")[0];
  // const height = el.clientHeight;
  // const width = el.clientWidth;
  // el.addEventListener("mousemove", handleMove);
  // function handleMove(e) {
  //   const xVal = e.layerX;
  //   const yVal = e.layerY;
  //   const yRotation = 20 * ((xVal - width / 2) / width);

  //   const xRotation = -20 * ((yVal - height / 2) / height);

  //   const string =
  //     "perspective(500px) scale(1.1) rotateX(" +
  //     xRotation +
  //     "deg) rotateY(" +
  //     yRotation +
  //     "deg)";

  //   el.style.transform = string;
  // }

  // el.addEventListener("mouseout", function () {
  //   el.style.transform = "perspective(500px) scale(1) rotateX(0) rotateY(0)";
  // });

  // el.addEventListener("mousedown", function () {
  //   el.style.transform =
  //     "perspective(500px) scale(0.9) rotateX(0) rotateY(0)";
  // });

  // el.addEventListener("mouseup", function () {
  //   el.style.transform =
  //     "perspective(500px) scale(1.1) rotateX(0) rotateY(0)";
  // });
  return (
    <div className={styles.container}>
      <Head>
        <title>Cengiz C. Mataracı Personal Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          className={styles.profile}
          src={Profile}
          alt="Profile Img"
          width={180}
          height={180}
        />

        <p className={styles.description}>
          Software Developer who is open to learn new technologies especially in
          web programming. Trying to improve React.js and Javascript. Working
          with the aim of improving his knowledge in these fields. Currently
          working at
          <a href="https://www.navlungo.com">
            <strong> Navlungo</strong>
          </a>{" "}
          as Software Developer
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </div>
  );
}
